# Generated by Django 3.1.4 on 2021-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_create_date',
        ),
        migrations.AddField(
            model_name='dishes',
            name='dishes_remake',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_remake',
            field=models.CharField(max_length=20),
        ),
    ]
